[package]
name = "copland"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "copland"
path = "src/lib.rs"

[[bin]]
name = "copland"
path = "src/bin.rs"

[dependencies]
num = "0.4.0"
