[package]
name = "copland"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "copland"
path = "src/bin.rs"

[dependencies]
num = "0.4"
thiserror = "1.0.40"
