name: "Clippy"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  clippy:
    runs-on: ubuntu-latest
    name: "[nightly] Clippy"
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy

      - run: cargo build

      - run: cargo clippy --lib --all-features

      - run: cargo clippy --lib -- -W clippy::pedantic -W clippy::nursery -W clippy::cargo

